import {
  DesignTokens,
  DraftCopy,
  EmailDesignDefinition,
  EmailDesignId,
  SampleData,
} from './types';

export const EMAIL_DESIGNS: EmailDesignDefinition[] = [
  {
    id: 'appointment-confirmed',
    label: 'Appointment Confirmed',
    category: 'Appointments',
    description: 'Sent when an inquiry is converted or manually booked.',
    event: 'APPOINTMENT_CONVERTED / MANUAL_BOOKING',
    fields: ['patientName', 'serviceName', 'doctorName', 'dateStr', 'timeRangeStr', 'appointmentId', 'baseUrl'],
  },
  {
    id: 'reminder-24h',
    label: '24-hour Reminder',
    category: 'Reminders',
    description: 'Sent 1 day before the scheduled appointment.',
    event: 'APPOINTMENT_REMINDER_24H',
    fields: ['patientName', 'serviceName', 'doctorName', 'dateStr', 'timeRangeStr', 'appointmentId', 'baseUrl'],
  },
  {
    id: 'reminder-48h',
    label: '48-hour Reminder',
    category: 'Reminders',
    description: 'Sent 2 days before the scheduled appointment.',
    event: 'APPOINTMENT_REMINDER_48H',
    fields: ['patientName', 'serviceName', 'doctorName', 'dateStr', 'timeRangeStr', 'appointmentId', 'baseUrl'],
  },
  {
    id: 'cancelled',
    label: 'Appointment Cancelled',
    category: 'Appointments',
    description: 'Confirmation when an appointment is cancelled.',
    event: 'CANCEL_BOOKING',
    fields: ['patientName', 'dateStr', 'cancellationReason'],
  },
  {
    id: 'rescheduled',
    label: 'Appointment Rescheduled',
    category: 'Appointments',
    description: 'Sent when appointment date/time is modified.',
    event: 'RESCHEDULE_BOOKING',
    fields: ['patientName', 'dateStr', 'timeRangeStr', 'baseUrl'],
  },
  {
    id: 'staff-reply',
    label: 'Staff Chat Reply',
    category: 'Conversation',
    description: 'Notification when clinic staff replies in chat.',
    event: 'STAFF_REPLIED_TO_CHAT',
    fields: ['patientName', 'baseUrl'],
  },
  {
    id: 'post-care',
    label: 'Post-care / Review',
    category: 'Follow-up',
    description: 'Sent after appointment completion for feedback.',
    event: 'APPOINTMENT_COMPLETED_POST_CARE',
    fields: ['patientName', 'serviceName', 'doctorName', 'dateStr', 'appointmentId', 'baseUrl'],
  },
  {
    id: 'booking-request-received',
    label: 'Booking Request Received',
    category: 'Inquiries',
    description: 'Sent to guest when their booking inquiry is received. (Not yet implemented)',
    event: 'INQUIRY_RECEIVED — pending implementation',
    fields: ['patientName'],
  },
  {
    id: 'request-rejected',
    label: 'Request Rejected',
    category: 'Inquiries',
    description: 'Sent when a guest inquiry is declined. (Not yet implemented)',
    event: 'REJECT_INQUIRY — pending implementation',
    fields: ['patientName', 'rejectionReason'],
  },
];

export const DEFAULT_TOKENS: DesignTokens = {
  primary: '#2563eb',
  accent: '#0f766e',
  canvas: '#eef2f7',
  card: '#ffffff',
  text: '#0f172a',
  muted: '#64748b',
  border: '#e2e8f0',
  buttonText: '#ffffff',
  radius: 16,
  density: 24,
  fontFamily: 'Arial, Helvetica, sans-serif',
};

export const DEFAULT_SAMPLE_DATA: SampleData = {
  patientName: 'Alice Guest',
  serviceName: 'Dental Consultation & Cleaning',
  doctorName: 'Dr. Adrian Samson',
  dateStr: 'Monday, June 22, 2026',
  timeRangeStr: '2:00 PM – 2:45 PM',
  appointmentId: 'APT-GUEST-2026-0622',
  baseUrl: 'http://localhost:3000',
  rejectionReason: 'Unfortunately, we are unable to accommodate your request at this time.',
  cancellationReason: 'This appointment has been cancelled as requested.',
};

export const PRESET_SCENARIOS: { label: string; data: SampleData }[] = [
  {
    label: 'Standard Guest',
    data: {
      patientName: 'Alice Guest',
      serviceName: 'Dental Consultation & Cleaning',
      doctorName: 'Dr. Adrian Samson',
      dateStr: 'Monday, June 22, 2026',
      timeRangeStr: '2:00 PM – 2:45 PM',
      appointmentId: 'APT-GUEST-2026-0622',
      baseUrl: 'http://localhost:3000',
      rejectionReason: 'Unfortunately, we are unable to accommodate your request at this time.',
      cancellationReason: 'This appointment has been cancelled as requested.',
    },
  },
  {
    label: 'Long Name Stress-Test',
    data: {
      patientName: 'Alexandria Marie Villanueva-Santos',
      serviceName: 'Comprehensive Orthodontic Consultation & Digital X-Ray',
      doctorName: 'Dr. Gabriella Montemayor-Samson',
      dateStr: 'Wednesday, September 30, 2026',
      timeRangeStr: '4:30 PM – 5:45 PM',
      appointmentId: 'APT-GUEST-2026-0930-LONG-REF-9921',
      baseUrl: 'https://samson-dental.com',
      rejectionReason: 'Unfortunately, we are unable to accommodate your request at this time.',
      cancellationReason: 'This appointment has been cancelled as requested.',
    },
  },
];

export const DEFAULT_COPY: Record<EmailDesignId, DraftCopy> = {
  'appointment-confirmed': {
    subject: 'Your Appointment is Confirmed',
    preheader: 'Your dental appointment has been successfully booked. View your visit details inside.',
    headerLabel: 'Appointment Confirmed',
    headline: 'Your Appointment is Confirmed',
    intro: "We are delighted to confirm your upcoming dental appointment at Samson Dental Center. Below are your visit details. Please review this information to ensure its accuracy.",
    ctaLabel: 'Open Clinic Chat',
    primaryInstruction: 'Please arrive 10 to 15 minutes before your scheduled time to complete check-in.',
    secondaryInstruction: '',
    footerText: 'Samson Dental Center • Caring for Your Smile',
    showSummary: true,
    showCta: true,
    showInstructions: true,
    showFooter: true,
  },
  'reminder-24h': {
    subject: 'Reminder: Your Appointment is Tomorrow',
    preheader: 'Your dental appointment is scheduled for tomorrow. View your details inside.',
    headerLabel: 'Appointment Reminder',
    headline: 'Your Appointment is Tomorrow',
    intro: "We're reaching out to remind you about your upcoming dental appointment with us at Samson Dental Center. Here are your visit details for tomorrow:",
    ctaLabel: 'Open Clinic Chat',
    primaryInstruction: 'Please arrive at least 10 minutes before your scheduled time.',
    secondaryInstruction: '',
    footerText: 'Samson Dental Center • Caring for Your Smile',
    showSummary: true,
    showCta: true,
    showInstructions: true,
    showFooter: true,
  },
  'reminder-48h': {
    subject: 'Reminder: Your Appointment is in 2 Days',
    preheader: 'Your dental appointment is coming up in 2 days. Review your visit details.',
    headerLabel: 'Appointment Reminder',
    headline: 'Your Appointment is in 2 Days',
    intro: "This is a friendly reminder about your upcoming dental appointment with us at Samson Dental Center. Here are your visit details:",
    ctaLabel: 'Open Clinic Chat',
    primaryInstruction: 'Please arrive at least 10 minutes before your scheduled time.',
    secondaryInstruction: '',
    footerText: 'Samson Dental Center • Caring for Your Smile',
    showSummary: true,
    showCta: true,
    showInstructions: true,
    showFooter: true,
  },
  cancelled: {
    subject: 'Your Appointment Has Been Cancelled',
    preheader: 'Your appointment cancellation has been processed. We hope to see you again soon.',
    headerLabel: 'Appointment Cancelled',
    headline: 'Your Appointment Has Been Cancelled',
    intro: 'We are writing to confirm that your appointment at Samson Dental Center has been cancelled as requested. We are sorry we will not be able to see you this time, and we hope to welcome you back soon.',
    ctaLabel: '',
    primaryInstruction: '',
    secondaryInstruction: '',
    footerText: 'Samson Dental Center • Caring for Your Smile',
    showSummary: false,
    showCta: false,
    showInstructions: false,
    showFooter: true,
  },
  rescheduled: {
    subject: 'Your Appointment Has Been Rescheduled',
    preheader: 'Your appointment has been moved to a new date and time. Review your updated schedule.',
    headerLabel: 'Appointment Rescheduled',
    headline: 'Your Appointment Has Been Rescheduled',
    intro: "We're writing to confirm that your appointment at Samson Dental Center has been successfully rescheduled. Here are your updated visit details:",
    ctaLabel: 'Open Clinic Chat',
    primaryInstruction: 'Please arrive 10 to 15 minutes before your scheduled time to complete check-in.',
    secondaryInstruction: '',
    footerText: 'Samson Dental Center • Caring for Your Smile',
    showSummary: true,
    showCta: true,
    showInstructions: true,
    showFooter: true,
  },
  'staff-reply': {
    subject: 'You Have a New Message',
    preheader: 'A member of our clinic team has sent you a message. Click to view and reply.',
    headerLabel: 'New Message',
    headline: 'A Message from Our Clinic Team',
    intro: 'A member of our clinic staff has sent you a reply regarding your appointment or inquiry. We are standing by to help.',
    ctaLabel: 'Open Clinic Chat',
    primaryInstruction: '',
    secondaryInstruction: '',
    footerText: 'Samson Dental Center • Caring for Your Smile',
    showSummary: false,
    showCta: true,
    showInstructions: false,
    showFooter: true,
  },
  'post-care': {
    subject: 'Thank You for Your Visit',
    preheader: 'We hope your visit went well. Your feedback means a lot to us.',
    headerLabel: 'Visit Complete',
    headline: 'Thank You for Your Visit',
    intro: 'Thank you for visiting Samson Dental Center. We hope your appointment went smoothly and that you are feeling great. Your experience is important to us, and we would love to hear how things went.',
    ctaLabel: 'Share Your Feedback',
    primaryInstruction: 'Please follow all post-treatment care instructions provided by your doctor.',
    secondaryInstruction: 'If you have any concerns or questions following your visit, please do not hesitate to reach out to our clinic anytime.',
    footerText: 'Samson Dental Center • Caring for Your Smile',
    showSummary: true,
    showCta: true,
    showInstructions: true,
    showFooter: true,
  },
  'booking-request-received': {
    subject: 'We\'ve Received Your Booking Request',
    preheader: 'Thank you for reaching out. We will review your request and be in touch shortly.',
    headerLabel: 'Booking Request Received',
    headline: 'We\'ve Received Your Booking Request',
    intro: 'Thank you for reaching out to Samson Dental Center. We have successfully received your booking request and our team is currently reviewing it. We will get back to you as soon as possible to confirm your appointment details.',
    ctaLabel: '',
    primaryInstruction: '',
    secondaryInstruction: '',
    footerText: 'Samson Dental Center • Caring for Your Smile',
    showSummary: false,
    showCta: false,
    showInstructions: false,
    showFooter: true,
  },
  'request-rejected': {
    subject: 'Update on Your Booking Request',
    preheader: 'An update regarding your recent booking request at Samson Dental Center.',
    headerLabel: 'Request Update',
    headline: 'Update on Your Booking Request',
    intro: 'Thank you for your interest in Samson Dental Center. After carefully reviewing your booking request, we regret to inform you that we are unable to accommodate your request at this time.',
    ctaLabel: '',
    primaryInstruction: '',
    secondaryInstruction: '',
    footerText: 'Samson Dental Center • Caring for Your Smile',
    showSummary: false,
    showCta: false,
    showInstructions: false,
    showFooter: true,
  },
};
