import {
  DesignTokens,
  DraftCopy,
  EmailDesignDefinition,
  EmailDesignId,
  SampleData,
} from './types';

export const EMAIL_DESIGNS: EmailDesignDefinition[] = [
  {
    id: 'appointment-confirmed',
    label: 'Appointment Confirmed',
    category: 'Appointments',
    description: 'Sent when an inquiry is converted or manually booked.',
    event: 'APPOINTMENT_CONVERTED / MANUAL_BOOKING',
    fields: ['patientName', 'serviceName', 'doctorName', 'dateStr', 'timeRangeStr', 'appointmentId', 'referenceCode', 'baseUrl', 'approvalReason'],
  },
  {
    id: 'reminder-24h',
    label: '24-hour Reminder',
    category: 'Reminders',
    description: 'Sent 1 day before the scheduled appointment.',
    event: 'APPOINTMENT_REMINDER_24H',
    fields: ['patientName', 'serviceName', 'doctorName', 'dateStr', 'timeRangeStr', 'appointmentId', 'baseUrl'],
  },
  {
    id: 'reminder-48h',
    label: '48-hour Reminder',
    category: 'Reminders',
    description: 'Sent 2 days before the scheduled appointment.',
    event: 'APPOINTMENT_REMINDER_48H',
    fields: ['patientName', 'serviceName', 'doctorName', 'dateStr', 'timeRangeStr', 'appointmentId', 'baseUrl'],
  },
  {
    id: 'cancelled',
    label: 'Appointment Cancelled',
    category: 'Appointments',
    description: 'Confirmation when an appointment is cancelled.',
    event: 'CANCEL_BOOKING',
    fields: ['patientName', 'serviceName', 'dateStr', 'timeRangeStr', 'appointmentId', 'referenceCode', 'cancellationReason', 'rebookUrl', 'baseUrl'],
  },
  {
    id: 'rescheduled',
    label: 'Appointment Rescheduled',
    category: 'Appointments',
    description: 'Sent when appointment date/time is modified.',
    event: 'RESCHEDULE_BOOKING',
    fields: ['patientName', 'serviceName', 'doctorName', 'oldDoctorName', 'oldServiceName', 'oldDateStr', 'oldTimeRangeStr', 'dateStr', 'timeRangeStr', 'appointmentId', 'referenceCode', 'baseUrl', 'rescheduleReason'],
  },
  {
    id: 'staff-reply',
    label: 'Staff Chat Reply',
    category: 'Conversation',
    description: 'Notification when clinic staff replies in chat.',
    event: 'STAFF_REPLIED_TO_CHAT',
    fields: ['patientName', 'baseUrl'],
  },
  {
    id: 'post-care',
    label: 'Post-care / Review',
    category: 'Follow-up',
    description: 'Sent after appointment completion for feedback.',
    event: 'APPOINTMENT_COMPLETED_POST_CARE',
    fields: ['patientName', 'serviceName', 'doctorName', 'dateStr', 'appointmentId', 'baseUrl'],
  },
  {
    id: 'booking-request-received',
    label: 'Booking Request Received',
    category: 'Inquiries',
    description: 'Sent to guest when their booking inquiry is received.',
    event: 'APPOINTMENT_INQUIRY_RECEIVED',
    fields: ['patientName', 'serviceName', 'dateStr', 'preferredStartTimeStr', 'appointmentId', 'patientNote'],
  },
  {
    id: 'request-rejected',
    label: 'Request Rejected',
    category: 'Inquiries',
    description: 'Sent when a guest inquiry is declined.',
    event: 'REJECT_INQUIRY',
    fields: ['patientName', 'serviceName', 'dateStr', 'preferredStartTimeStr', 'rejectionReason', 'rebookUrl'],
  },
  {
    id: 'no-show',
    label: 'Missed Appointment (No-show)',
    category: 'Follow-up',
    description: 'Sent when a patient misses their appointment.',
    event: 'APPOINTMENT_NO_SHOW',
    fields: ['patientName', 'serviceName', 'doctorName', 'dateStr', 'timeRangeStr', 'appointmentId', 'baseUrl'],
  },
];

export const DEFAULT_TOKENS: DesignTokens = {
  primary: '#2563eb',
  accent: '#0f766e',
  canvas: '#eef2f7',
  card: '#ffffff',
  text: '#0f172a',
  muted: '#64748b',
  border: '#e2e8f0',
  buttonText: '#ffffff',
  radius: 16,
  density: 24,
  fontFamily: 'Arial, Helvetica, sans-serif',
};

export const DEFAULT_SAMPLE_DATA: SampleData = {
  patientName: 'Alice Guest',
  serviceName: 'Dental Consultation & Cleaning',
  doctorName: 'Dr. Adrian Samson',
  dateStr: 'Monday, June 22, 2026',
  timeRangeStr: '2:00 PM – 2:45 PM',
  appointmentId: 'd9b7f54c-1111-4444-9999-555555555555',
  referenceCode: 'SDC-8921',
  oldDoctorName: 'Dr. Adrian Samson',
  oldServiceName: 'General Consultation',
  oldDateStr: 'Monday, June 15, 2026',
  oldTimeRangeStr: '9:00 AM – 9:30 AM',
  calendarAddUrl: 'https://calendar.google.com/calendar/render?action=TEMPLATE&text=Samson%20Dental%20Appointment',
  googleMapsUrl: 'https://maps.google.com/?q=Samson+Dental+Center,+Quezon+City',
  rebookUrl: 'http://localhost:3000/book',
  baseUrl: 'http://localhost:3000',
  rejectionReason: 'Unfortunately, we are unable to accommodate your request at this time.',
  cancellationReason: 'Clinic schedule conflict.',
  preferredStartTimeStr: '2:00 PM',
  patientNote: 'Prefer mornings if possible.',
  approvalReason: 'Slot confirmed by clinic',
  rescheduleReason: 'Patient requested new date',
  checkoutNote: 'Treatment completed and reviewed with patient',
};

export const PRESET_SCENARIOS: { label: string; data: SampleData }[] = [
  {
    label: 'Standard Guest',
    data: {
      patientName: 'Alice Guest',
      serviceName: 'Dental Consultation & Cleaning',
      doctorName: 'Dr. Adrian Samson',
      dateStr: 'Monday, June 22, 2026',
      timeRangeStr: '2:00 PM – 2:45 PM',
      appointmentId: 'd9b7f54c-1111-4444-9999-555555555555',
      referenceCode: 'SDC-8921',
      oldDoctorName: 'Dr. Adrian Samson',
      oldServiceName: 'General Consultation',
      oldDateStr: 'Monday, June 15, 2026',
      oldTimeRangeStr: '9:00 AM – 9:30 AM',
      calendarAddUrl: 'https://calendar.google.com/calendar/render?action=TEMPLATE&text=Samson%20Dental%20Appointment',
      googleMapsUrl: 'https://maps.google.com/?q=Samson+Dental+Center,+Quezon+City',
      rebookUrl: 'http://localhost:3000/book',
      baseUrl: 'http://localhost:3000',
      rejectionReason: 'Unfortunately, we are unable to accommodate your request at this time.',
      cancellationReason: 'Clinic schedule conflict — please contact us to rebook.',
      preferredStartTimeStr: '2:00 PM',
      patientNote: 'Prefer mornings if possible.',
      approvalReason: 'Slot confirmed by clinic',
      rescheduleReason: 'Patient requested new date',
      checkoutNote: 'Treatment completed and reviewed with patient',
    },
  },
  {
    label: 'Long Name Stress-Test',
    data: {
      patientName: 'Alexandria Marie Villanueva-Santos',
      serviceName: 'Comprehensive Orthodontic Consultation & Digital X-Ray',
      doctorName: 'Dr. Gabriella Montemayor-Samson',
      dateStr: 'Wednesday, September 30, 2026',
      timeRangeStr: '4:30 PM – 5:45 PM',
      appointmentId: 'a1b2c3d4-2222-4444-9999-666666666666',
      referenceCode: 'SDC-9931',
      oldDoctorName: 'Dr. Gabriella Montemayor-Samson',
      oldServiceName: 'Initial Orthodontic Assessment',
      oldDateStr: 'Wednesday, September 23, 2026',
      oldTimeRangeStr: '3:00 PM – 4:15 PM',
      calendarAddUrl: 'https://calendar.google.com/calendar/render?action=TEMPLATE&text=Samson%20Dental%20Appointment',
      googleMapsUrl: 'https://maps.google.com/?q=Samson+Dental+Center,+Quezon+City',
      rebookUrl: 'https://samson-dental.com/book',
      baseUrl: 'https://samson-dental.com',
      rejectionReason: 'Unfortunately, we are unable to accommodate your request at this time.',
      cancellationReason: 'Clinic schedule conflict.',
      preferredStartTimeStr: '2:00 PM',
      patientNote: 'Prefer mornings if possible.',
      approvalReason: 'Slot confirmed by clinic',
      rescheduleReason: 'Patient requested new date',
      checkoutNote: 'Treatment completed and reviewed with patient',
    },
  },
];

export const DEFAULT_COPY: Record<EmailDesignId, DraftCopy> = {
  'appointment-confirmed': {
    subject: 'Your Appointment is Confirmed',
    preheader: 'Please review your visit schedule and check-in reminders.',
    headerLabel: 'Appointment Confirmed',
    headline: 'Your Appointment is Confirmed',
    intro: "Your appointment at Samson Dental Center is confirmed. Please review the visit details below.",
    ctaLabel: 'Add to Calendar',
    primaryInstruction: 'Arrive 10-15 minutes early for check-in. Bring a valid ID.',
    secondaryInstruction: '',
    footerText: 'Samson Dental Center • Caring for Your Smile',
    showSummary: true,
    showCta: true,
    showInstructions: true,
    showFooter: true,
  },
  'reminder-24h': {
    subject: 'Reminder: Your Appointment is Tomorrow',
    preheader: 'We look forward to seeing you. Please arrive 10-15 minutes early.',
    headerLabel: 'Appointment Reminder',
    headline: 'Your Appointment is Tomorrow',
    intro: "A friendly reminder about your dental appointment at Samson Dental Center tomorrow. Here are your visit details:",
    ctaLabel: 'Open Clinic Chat',
    primaryInstruction: '',
    secondaryInstruction: '',
    footerText: 'Samson Dental Center • Caring for Your Smile',
    showSummary: true,
    showCta: true,
    showInstructions: false,
    showFooter: true,
  },
  'reminder-48h': {
    subject: 'Reminder: Your Appointment is in 2 Days',
    preheader: 'Need to reschedule or have questions? Contact our clinic team.',
    headerLabel: 'Appointment Reminder',
    headline: 'Your Appointment is in 2 Days',
    intro: "A friendly reminder about your dental appointment at Samson Dental Center in 2 days. Here are your visit details:",
    ctaLabel: 'Open Clinic Chat',
    primaryInstruction: '',
    secondaryInstruction: '',
    footerText: 'Samson Dental Center • Caring for Your Smile',
    showSummary: true,
    showCta: true,
    showInstructions: false,
    showFooter: true,
  },
  cancelled: {
    subject: 'Your Appointment Has Been Cancelled',
    preheader: 'We hope to see you again soon. Feel free to rebook whenever you are ready.',
    headerLabel: 'Appointment Cancelled',
    headline: 'Your Appointment Has Been Cancelled',
    intro: "Your appointment at Samson Dental Center has been cancelled. Please see the appointment details below.",
    ctaLabel: '',
    primaryInstruction: '',
    secondaryInstruction: '',
    footerText: 'Samson Dental Center • Caring for Your Smile',
    showSummary: false,
    showCta: false,
    showInstructions: false,
    showFooter: true,
  },
  rescheduled: {
    subject: 'Your Appointment Has Been Rescheduled',
    preheader: 'Please review your updated clinic date, time, and location.',
    headerLabel: 'Appointment Rescheduled',
    headline: 'Your Appointment Has Been Rescheduled',
    intro: "Your appointment at Samson Dental Center has been rescheduled. Please see your new visit details below.",
    ctaLabel: 'Update Calendar',
    primaryInstruction: '',
    secondaryInstruction: '',
    footerText: 'Samson Dental Center • Caring for Your Smile',
    showSummary: true,
    showCta: true,
    showInstructions: true,
    showFooter: true,
  },
  'staff-reply': {
    subject: 'You Have a New Message',
    preheader: 'Our clinic team just replied to your message. Click to open your chat.',
    headerLabel: 'New Message',
    headline: 'A Message from Our Clinic Team',
    intro: 'A member of our clinic staff has sent you a message about your appointment. We are standing by to help.',
    ctaLabel: 'Open Clinic Chat',
    primaryInstruction: '',
    secondaryInstruction: '',
    footerText: 'Samson Dental Center • Caring for Your Smile',
    showSummary: false,
    showCta: true,
    showInstructions: false,
    showFooter: true,
  },
  'post-care': {
    subject: 'Thank You for Your Visit',
    preheader: 'We hope your visit went smoothly. Please share how your experience was.',
    headerLabel: 'Visit Complete',
    headline: 'Thank You for Your Visit',
    intro: 'Thank you for visiting Samson Dental Center. We hope your visit went smoothly and that you are feeling great.',
    ctaLabel: 'Share Your Feedback',
    primaryInstruction: '',
    secondaryInstruction: '',
    footerText: 'Samson Dental Center • Caring for Your Smile',
    showSummary: true,
    showCta: true,
    showInstructions: false,
    showFooter: true,
  },
  'booking-request-received': {
    subject: 'We\'ve Received Your Booking Request',
    preheader: 'Our staff is reviewing your requested time. We will reach out shortly.',
    headerLabel: 'Booking Request Received',
    headline: 'We\'ve Received Your Booking Request',
    intro: 'Thank you for reaching out to Samson Dental Center. Your booking request has been received, and our staff is reviewing it.',
    ctaLabel: '',
    primaryInstruction: '',
    secondaryInstruction: '',
    footerText: 'Samson Dental Center • Caring for Your Smile',
    showSummary: false,
    showCta: false,
    showInstructions: false,
    showFooter: true,
  },
  'request-rejected': {
    subject: 'Update on Your Booking Request',
    preheader: 'We cannot accommodate this request. Contact our clinic to explore other options.',
    headerLabel: 'Request Update',
    headline: 'Update on Your Booking Request',
    intro: 'Thank you for your interest in Samson Dental Center. After carefully reviewing your booking request, we regret to inform you that we are unable to accommodate your request at this time.',
    ctaLabel: '',
    primaryInstruction: '',
    secondaryInstruction: '',
    footerText: 'Samson Dental Center • Caring for Your Smile',
    showSummary: false,
    showCta: false,
    showInstructions: false,
    showFooter: true,
  },
  'no-show': {
    subject: 'We Missed You at Your Appointment',
    preheader: 'Life happens. Tell us what happened, and rebook whenever you are ready.',
    headerLabel: 'Missed Appointment',
    headline: 'We Missed You at Your Appointment',
    intro: "We missed you at your appointment at Samson Dental Center. We understand that things come up, so please review the details below and reach out whenever you are ready.",
    ctaLabel: 'Tell Us What Happened',
    primaryInstruction: '',
    secondaryInstruction: '',
    footerText: 'Samson Dental Center • Caring for Your Smile',
    showSummary: true,
    showCta: true,
    showInstructions: false,
    showFooter: true,
  },
};
